# -*- coding: utf-8 -*-
"""Assignment7_Ashutosh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GViC3N0pqZKCrrKBhSIaDwhBOJ0DkCme
"""

!pip install -q \
langchain \
langchain-core \
langchain-community \
langchain-openai \
langchain-huggingface \
transformers \
sentence-transformers \
accelerate \
bitsandbytes \
huggingface_hub \
faiss-cpu \
chromadb \
pypdf \
pymupdf \
unstructured \
python-docx \
pandas \
python-dotenv \
tiktoken \
openai \
gradio \
ragas \
datasets \
tqdm

"""##install all libraries"""

import langchain
import faiss
import transformers
import sentence_transformers

print("Everything is working!")
!pip install -q langchain_text_splitters

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_huggingface import HuggingFaceEndpoint

from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

"""##huggging face embedding model and gemini for response"""

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint

from langchain_huggingface import HuggingFaceEndpoint

!pip install -q langchain-google-genai
from langchain_google_genai import ChatGoogleGenerativeAI

from google.colab import userdata
import os

os.environ["GOOGLE_API_KEY"] =userdata.get("GOOGLE_API_KEY")

embedding = HuggingFaceEmbeddings(

    model_name="sentence-transformers/all-MiniLM-L6-v2"

)

"""##check the llm"""

llm = ChatGoogleGenerativeAI(

    model="gemini-2.5-flash",

    temperature=0

)

print(llm.invoke("capital of india").content)

"""##load the external pdf files using pypdf loader"""

from langchain_community.document_loaders import PyPDFLoader
loader=PyPDFLoader("dl-curriculum.pdf")
doc=loader.load()


##check pdf is load or not


print(len(doc))
print(doc[0].page_content)

"""##spliiting the text using recursive character text splitter"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter=RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50,

)

chunks=splitter.split_documents(doc)
len(chunks)

"""##creating vector store"""

vector_store=FAISS.from_documents(documents=chunks,embedding=embedding)

"""##implemanting retriver"""

retriver=vector_store.as_retriever(search_kwargs={"k":2})

"""##user query"""

query="what is this PDF about?"
documents=retriver.invoke(query)

 ##chech the document

for doc in documents:
  print(doc.page_content)

"""##final answer"""

context="\n\n".join([doc.page_content for doc in documents ])


##prompt

prompt=f"""Anser the question using only the context below.

context:
{context}

question:
{query}
"""

response=llm.invoke(prompt)
print(response.content)

